### ISSUE TITLE
 python - py-expression-eval - Passing a numpy ndarray

### ISSUE THREAD

**Issue by inxp** [Axiacore/py-expression-eval#19]
I am using py-expression-eval library for evaluating an expression.

```
from py-expression-eval import Parser
parser=Parser()
a = np.array([1,2,3])
parser.parse('x*5').evaluate({'x':a})
#Works and outputs
array([  5.,  10.,  15.])
```

However
```
parser.parse('sin(x)').evaluate({'x':a})
#Throws a error
Traceback (most recent call last):
File "<pyshell#52>", line 1, in <module>
parser.parse('sin(x)').evaluate({'x':a})
File "C:\Python27\lib\site-packages\py_expression_eval\__init__.py", line 133, in evaluate
nstack.append(f(n1))
TypeError: only length-1 arrays can be converted to Python scalars
```

But if I pass values of array one by one it works
```
parser.parse('sin(x)').evaluate({'x':a[0]})
0.8414709848078965
```

[StackOverflow link](http://stackoverflow.com/questions/41207865/python-py-expression-eval-passing-a-numpy-ndarray)

**Comment by inxp** [comment]
Replacing inbuilt math sin function with np
`parser.ops1['sin'] = np.sin`
Now it works
