### ISSUE TITLE
No way to pass mix of scalars and lists to function

### ISSUE THREAD

**Issue by z0u** [Axiacore/py-expression-eval#22]
Lists are flattened, so there's no way to pass in an entire list as an argument to a function.

```python
def f(xs, y):
     return sum(x + y for x in xs)

f([1,2,3], 2)
# 12

parser.evaluate("f(xs, y)", variables={"f": f, "xs": [1,2,3], "y": 2})
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py_expression_eval/__init__.py", line 494, in evaluate
    return self.parse(expr).evaluate(variables)
  File "py_expression_eval/__init__.py", line 138, in evaluate
    nstack.append(f(*n1))
TypeError: f() takes 2 positional arguments but 4 were given
```

**Comment by willstott101** [comment]
In this example you could use `f(y, *xs)` but of course it would still be impossible to have two lists as parameters.
