### ISSUE TITLE
toString() it's not working with negative numbers

### ISSUE THREAD

**Issue by magdy-zon** [Axiacore/py-expression-eval#27]
# Hi my friend!

 I was working perfectly with your library until I had a trouble with a simple example:
When I was trying to parse '-1' I do:

`>>> parser.parse('-1').toString()`

Shows an error:
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/py_expression_eval/__init__.py", line 185, in toString
    nstack.append('(' + f + n1 + ')')
TypeError: cannot concatenate 'str' and 'float' objects**

Thanks for read my issue and have good code lines.

**Comment by flotwig** [comment]
A similar issue happens when you try to use `toString()` on an expression that uses functions, it says that `TypeError: must be str, not float` on line 187.
